<a href="https://colab.research.google.com/github/Viny2030/Libro_Algoritmos_contra_fraude_corrupcion/blob/main/datasetlibro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###-ALGORITHM I-

In [1]:
!pip install faker

Collecting faker
  Downloading faker-37.3.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.2)
Downloading faker-37.3.0-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 20.5 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-37.3.0

In [4]:
import pandas as pd
from faker import Faker
import random
import datetime

fake = Faker()

num_records = 30

data_ecommerce = {
    'Transaction_ID': range(1, num_records + 1),
    'Amount': [round(random.uniform(10, 15000), 2) for _ in range(num_records)],
    'Date_Time': [fake.date_time_between(start_date='-1y', end_date='now') for _ in range(num_records)],
    'User_ID': [fake.user_name() for _ in range(num_records)],
    'IP_Address': [fake.ipv4_private() if random.random() < 0.8 else fake.ipv4_public() for _ in range(num_records)],
    'Product': [random.choice(['Laptop', 'Book', 'T-shirt', 'Shoes', 'Television', 'Headphones', 'Backpack', 'Watch', 'Smartphone', 'Charger']) for _ in range(num_records)],
    'Is_Fraudulent': [0] * num_records  # Initialize all transactions as non-fraudulent
}

df_ecommerce = pd.DataFrame(data_ecommerce)
df_ecommerce['Date_Time'] = pd.to_datetime(df_ecommerce['Date_Time']) # Convert the column to datetime

# Mark nighttime transactions as fraudulent
for index, row in df_ecommerce.iterrows():
    if row['Date_Time'].hour >= 21:
        df_ecommerce.at[index, 'Is_Fraudulent'] = 1

csv_filename = 'df_ecommerce.csv'
df_ecommerce.to_csv(csv_filename, index=False)

print(f"The DataFrame has been successfully saved to the file '{csv_filename}'")
df_ecommerce

The DataFrame has been successfully saved to the file 'df_ecommerce.csv'

,Transaction_ID,Amount,Date_Time,User_ID,IP_Address,Product,Is_Fraudulent
0,1,9864.48,2024-12-31 13:38:39.874220,heidichase,192.168.104.70,Charger,0
1,2,4042.04,2025-04-08 21:28:40.551705,lmiranda,192.168.237.213,T-shirt,1
2,3,477.49,2025-05-18 15:57:24.688353,zreese,10.3.132.230,Shoes,0
3,4,835.04,2025-03-06 17:34:17.693536,adammendoza,172.27.31.250,Charger,0
4,5,14063.93,2024-10-10 18:19:05.466110,rochaedward,172.17.54.119,Book,0
5,6,12149.20,2025-03-11 22:54:23.606329,sandra00,88.20.162.106,Smartphone,1
6,7,14205.28,2024-08-05 18:45:34.496300,lharrison,88.88.168.137,Backpack,0
7,8,7715.90,2024-12-10 01:27:51.081023,jgonzalez,10.87.223.126,Smartphone,0
8,9,5281.65,2024-11-27 17:59:46.609480,dprice,172.16.252.126,Backpack,0
9,10,6267.39,2025-06-01 10:41:07.991663,meaganwalton,192.168.57.43,Charger,0
10,11,10742.79,2024-08-29 21:00:31.328928,harmonanthony,10.144.135.200,Television,1
11,12,8436.28,2024-07-22 21:54:39.494276,daniel81,52.183.225.24,Television,1
12,13,10715.06,2024-09-22 02:08:54.435513,carsonjames,172.19.179.77,Smartphone,0
13,14,8429.86,2024-07-27 17:41:44.817805,oevans,10.124.237.141,Smartphone,0
14,15,6794.81,2024-09-03 01:28:12.449911,laurawhite,172.29.145.42,Laptop,0
15,16,11034.91,2025-04-18 17:07:02.472738,karen11,10.188.174.33,Shoes,0
16,17,14774.96,2025-03-26 19:58:18.294975,sierra36,192.168.87.25,Laptop,0
17,18,554.63,2024-10-10 05:35:43.292841,ewagner,10.139.255.138,Smartphone,0
18,19,6348.49,2024-08-13 13:56:52.951666,guzmankaren,192.168.146.48,Smartphone,0
19,20,9513.23,2025-04-20 02:10:55.349702,santosgina,172.20.113.3,Charger,0
20,21,560.90,2024-10-09 06:50:49.449376,tcurry,71.34.225.88,Smartphone,0
21,22,2953.04,2024-06-17 08:27:39.443840,mcollier,172.16.228.132,Backpack,0
22,23,8472.21,2024-11-20 14:42:41.896182,judyaguilar,192.168.48.224,Laptop,0
23,24,12020.76,2025-03-07 14:41:35.210076,marydelgado,10.89.7.208,T-shirt,0
24,25,2680.74,2024-09-10 01:06:28.929370,ehicks,203.227.27.227,Headphones,0
25,26,11641.01,2024-08-13 18:28:30.079734,veronica01,192.168.214.242,Charger,0
26,27,3944.85,2024-08-03 04:45:36.361614,nmccormick,172.23.246.228,Charger,0
27,28,5526.15,2024-09-26 09:36:01.293489,zsuarez,192.168.231.206,Backpack,0
28,29,9184.30,2024-06-18 12:04:19.643453,znelson,10.163.12.214,Watch,0
29,30,11693.15,2025-05-21 21:26:23.360110,cpeters,123.218.88.208,Watch,1

### ALGORITHM II-

In [9]:
import pandas as pd
import numpy as np
from faker import Faker
import random

# --- CRUCIAL CHANGE HERE ---
# Initialize Faker with an explicit English locale to ensure English names.
# Use 'en_US' for American English names
# Use 'en_GB' for British English names
# Use 'en' for a more generic set of English names
fake = Faker('en_US') # Changed from 'es_AR' to 'en_US'

num_reports = 30 # Renamed for clarity, corresponds to num_rendiciones
# Assuming 'num_contratos' was a typo and should be 'num_reports' here based on context
amounts = np.random.uniform(1000, 50000, num_reports)
formatted_amounts = ["{:.2f}".format(amount) for amount in amounts]

data_expense_reports = {
    'Report_ID': range(1, num_reports + 1),
    'Submission_Date': pd.to_datetime([fake.date_between(start_date='-365d', end_date='today') for _ in range(num_reports)]),
    'Employee': [fake.name() for _ in range(num_reports)], # This will now produce English names
    'Department': [random.choice(['Sales', 'Marketing', 'Purchasing', 'HR', 'Finance']) for _ in range(num_reports)],
    'Expense_Type': [random.choice(['Travel Expenses', 'Office Supplies', 'Lunch', 'Transportation', 'Other']) for _ in range(num_reports)],
    'Description': [random.choice(['expenses', 'travel_expenses', 'purchases', 'general_expenses']) for _ in range(num_reports)],
    'Amount': formatted_amounts,
    'Receipt_Attached': [random.choice(['Yes', 'No', 'Partial']) for _ in range(num_reports)],
    'Approval_Status': [random.choice(['Approved', 'Pending', 'Rejected']) for _ in range(num_reports)],
    'Is_Suspicious': np.zeros(num_reports, dtype=int) # This will be overwritten below
}

df_expense_reports = pd.DataFrame(data_expense_reports)

# Correction here: correct comparison for flagging as suspicious
# An expense is suspicious if no receipt is attached OR if its approval status is 'Rejected'.
df_expense_reports['Is_Suspicious'] = np.where(
    (df_expense_reports['Receipt_Attached'] == 'No') |
    (df_expense_reports['Approval_Status'] == 'Rejected'),
    1, # Mark as suspicious
    0  # Mark as not suspicious
)

csv_filename = 'df_surrenders1.csv' # Keeping original filename for consistency with the prompt
df_expense_reports.to_csv(csv_filename, index=False)

print(f"The DataFrame has been successfully saved to the file '{csv_filename}'")
print("\nFirst 5 rows of the generated DataFrame (to check names):")
print(df_expense_reports.head())

The DataFrame has been successfully saved to the file 'df_surrenders1.csv'

First 5 rows of the generated DataFrame (to check names):
   Report_ID Submission_Date       Employee  Department     Expense_Type  \
0          1      2025-04-19  Kathryn Davis  Purchasing  Travel Expenses
1          2      2025-03-01  Sherri Foster  Purchasing   Transportation
2          3      2024-07-22    Tammy Davis     Finance            Lunch
3          4      2024-08-22   Patrick Nash  Purchasing  Office Supplies
4          5      2024-07-13   Joshua James  Purchasing  Travel Expenses

        Description    Amount Receipt_Attached Approval_Status  Is_Suspicious
0          expenses  48570.45          Partial        Rejected              1
1          expenses  43889.48              Yes         Pending              0
2          expenses  38807.68              Yes        Rejected              1
3  general_expenses   4477.03               No         Pending              1
4   travel_expenses  33072.31              Yes        Rejected              1

In [8]:
import pandas as pd
import numpy as np
from faker import Faker
import random

# Initialize Faker for Spanish (Argentina) locale
fake = Faker('es_AR')

num_reports = 30 # Renamed for clarity, corresponds to num_rendiciones
# Assuming 'num_contratos' was a typo and should be 'num_reports' here based on context
amounts = np.random.uniform(1000, 50000, num_reports)
formatted_amounts = ["{:.2f}".format(amount) for amount in amounts]

data_expense_reports = {
    'Report_ID': range(1, num_reports + 1),
    'Submission_Date': pd.to_datetime([fake.date_between(start_date='-365d', end_date='today') for _ in range(num_reports)]),
    'Employee': [fake.name() for _ in range(num_reports)], # This will now produce English names,
    'Department': [random.choice(['Sales', 'Marketing', 'Purchasing', 'HR', 'Finance']) for _ in range(num_reports)],
    'Expense_Type': [random.choice(['Travel Expenses', 'Office Supplies', 'Lunch', 'Transportation', 'Other']) for _ in range(num_reports)],
    'Description': [random.choice(['expenses', 'travel_expenses', 'purchases', 'general_expenses']) for _ in range(num_reports)],
    'Amount': formatted_amounts,
    'Receipt_Attached': [random.choice(['Yes', 'No', 'Partial']) for _ in range(num_reports)],
    'Approval_Status': [random.choice(['Approved', 'Pending', 'Rejected']) for _ in range(num_reports)],
    'Is_Suspicious': np.zeros(num_reports, dtype=int)
}

df_expense_reports = pd.DataFrame(data_expense_reports)

# Correction here: correct comparison for flagging as suspicious
df_expense_reports['Is_Suspicious'] = np.where(
    (df_expense_reports['Receipt_Attached'] == 'No') | (df_expense_reports['Approval_Status'] == 'Rejected'),
    1, # Mark as suspicious
    0  # Mark as not suspicious
)

csv_filename = 'df_surrenders1.csv' # Keeping original filename for consistency with the prompt
df_expense_reports.to_csv(csv_filename, index=False)

print(f"The DataFrame has been successfully saved to the file '{csv_filename}'")
print(df_expense_reports)

The DataFrame has been successfully saved to the file 'df_surrenders1.csv'
    Report_ID Submission_Date                                     Employee  \
0           1      2024-09-14                                 Thiago Ortiz
1           2      2024-12-20                      Francesca Julian Romero
2           3      2025-03-04                       Lisandro Romero Juarez
3           4      2025-01-12                       Ian Benjamin Rodriguez
4           5      2024-08-08                     Sr(a). Catalina Gonzalez
5           6      2024-11-30                      Ana Paula Santiago Cruz
6           7      2024-11-07                        Juan Martin Fernandez
7           8      2024-12-13                       Juan Pablo Ojeda Rojas
8           9      2025-03-12                                   Elena Rios
9          10      2024-10-01                      Isabella Perez Gonzalez
10         11      2025-03-13                       Sr(a). Sofia Fernandez
11         12      2024-07-07                        Dr(a). Lautaro Juarez
12         13      2024-12-18                         Ian Benjamin Coronel
13         14      2024-07-09                                Felipe Suarez
14         15      2025-04-14                    Valentino Gonzalez Rivero
15         16      2024-09-06                            Lola Tomàs Guzman
16         17      2025-02-07              Constantino Uma  Ramirez Acosta
17         18      2024-12-12                          Mora Lara Fernandez
18         19      2024-07-04                 Thiago Valentin Ignacio Ruiz
19         20      2025-03-27                        Dr(a). Victoria Perez
20         21      2024-08-14                                   Ian Correa
21         22      2025-03-16                         Abril Joaquin Medina
22         23      2024-11-08             Valentina  Lucas Navarro Miranda
23         24      2024-10-12                         Ana Paula Alma Lopez
24         25      2025-04-19          Thiago Ezequiel Abigail Rios Rivero
25         26      2025-02-15                          Olivia Matias Gomez
26         27      2024-07-20                 Isabella Thiago Nahuel Acuña
27         28      2025-02-10                       Pilar Benicio Gonzalez
28         29      2025-01-07  Maria Victoria Catalina Velazquez Fernandez
29         30      2025-01-25                       Sr(a). Lourdes Vazquez

    Department     Expense_Type       Description    Amount Receipt_Attached  \
0    Marketing   Transportation   travel_expenses   7738.00              Yes
1           HR            Other   travel_expenses  45489.77          Partial
2   Purchasing  Travel Expenses  general_expenses  19151.07               No
3   Purchasing  Office Supplies   travel_expenses   9622.16               No
4        Sales  Travel Expenses  general_expenses   9923.52          Partial
5        Sales            Other   travel_expenses   7444.20               No
6    Marketing  Travel Expenses  general_expenses  24958.48              Yes
7        Sales  Office Supplies         purchases  23246.81          Partial
8        Sales            Other  general_expenses  14657.22              Yes
9           HR            Other         purchases  14153.85               No
10  Purchasing            Other  general_expenses  44394.31          Partial
11       Sales            Lunch          expenses  35260.23              Yes
12   Marketing            Other   travel_expenses   9154.84               No
13  Purchasing            Lunch          expenses  38473.30               No
14       Sales  Travel Expenses         purchases  17582.17          Partial
15     Finance            Other   travel_expenses  35325.14               No
16          HR            Lunch   travel_expenses  45463.92              Yes
17  Purchasing  Travel Expenses   travel_expenses   1855.18          Partial
18          HR  Travel Expenses   travel_expenses  15408.71               No
19   Marketing  Travel Expenses  general_expenses  14934.66              Yes
20       Sales   Transportation         purchases  49897.67              Yes
21     Finance            Lunch   travel_expenses  30245.08              Yes
22     Finance   Transportation   travel_expenses  41177.71              Yes
23  Purchasing            Lunch          expenses   5862.50              Yes
24   Marketing            Other          expenses  30901.83              Yes
25   Marketing  Travel Expenses  general_expenses  17514.26              Yes
26   Marketing  Office Supplies         purchases  13009.59               No
27       Sales  Office Supplies  general_expenses  18629.69               No
28          HR            Other   travel_expenses  12734.75               No
29          HR            Other   travel_expenses  34395.11               No

   Approval_Status  Is_Suspicious
0         Approved              0
1         Rejected              1
2          Pending              1
3          Pending              1
4         Rejected              1
5         Approved              1
6         Approved              0
7         Approved              0
8         Approved              0
9         Rejected              1
10        Approved              0
11        Approved              0
12        Rejected              1
13         Pending              1
14        Rejected              1
15         Pending              1
16         Pending              0
17         Pending              0
18        Rejected              1
19        Approved              0
20         Pending              0
21        Rejected              1
22         Pending              0
23         Pending              0
24         Pending              0
25        Rejected              1
26         Pending              1
27        Approved              1
28         Pending              1
29        Rejected              1

###-ALGORITHM III-

In [11]:
import random
from faker import Faker
import numpy as np
import pandas as pd

# 1. Generate a simulated dataset for political corruption
fake = Faker('en_US') # Changed to 'en_US' for English names/words

num_politicians = 30
amounts = np.random.uniform(5000, 10000000, num_politicians)
formatted_amounts = [f"{amount:.2f}" for amount in amounts]

political_data = {
    'Politician_ID': range(1, num_politicians + 1),
    'Full_Name': [fake.name() for _ in range(num_politicians)],
    'Position': [random.choice(['Representative', 'Senator', 'Minister', 'Mayor', 'Councilor']) for _ in range(num_politicians)],
    'Political_Party': [fake.word().capitalize() + ' Party' for _ in range(num_politicians)],
    'Activity_Period': [f"{random.randint(2018, 2024)}-{random.randint(2020, 2025)}" for _ in range(num_politicians)],
    'Last_Year_Asset_Declaration': formatted_amounts,
    'Last_Year_Asset_Increase_Percentage': np.random.choice([0.10, 0.20, 0.30, 0.40], num_politicians),
    'Donations_Received': np.round(np.random.uniform(0, 150000, num_politicians), 2),
    'Campaign_Expenses': np.round(np.random.uniform(10000, 250000, num_politicians), 2),
    'Business_Ties': [random.choice(['Yes', 'No', 'Declared']) for _ in range(num_politicians)],
    'Previous_Complaints': np.random.randint(0, 3, num_politicians),
    'Is_Suspicious': np.zeros(num_politicians, dtype=int)  # Initially not suspicious
}

df_politicians = pd.DataFrame(political_data)

# Update Is_Suspicious based on conditions
# A politician is marked suspicious if:
# 1. Their asset increase percentage in the last year is greater than 10%
# 2. They have declared business ties ('Yes')
# 3. They have exactly 1 previous complaint
df_politicians['Is_Suspicious'] = np.where(
    (df_politicians['Last_Year_Asset_Increase_Percentage'] > 0.05) &
    (df_politicians['Business_Ties'] == 'Yes') &
    (df_politicians['Previous_Complaints'] == 1),
    1, # Set to 1 if all conditions are met
    0  # Otherwise, set to 0
)

csv_file_name = 'df_politicians.csv'
df_politicians.to_csv(csv_file_name, index=False)

print(f"The DataFrame has been successfully saved to the file '{csv_file_name}'")
print(df_politicians.head()) # Print the first few rows to verify

The DataFrame has been successfully saved to the file 'df_politicians.csv'
   Politician_ID         Full_Name        Position Political_Party  \
0              1    Cynthia Medina  Representative      Care Party
1              2  April Fitzgerald           Mayor     Order Party
2              3   George Williams           Mayor      Like Party
3              4        Nancy Dean        Minister  Attorney Party
4              5   Kimberly Lester  Representative      Near Party

  Activity_Period Last_Year_Asset_Declaration  \
0       2019-2020                  8161793.09
1       2019-2024                  5016935.53
2       2020-2022                  5877579.06
3       2021-2025                  9767541.79
4       2020-2023                  7233355.25

   Last_Year_Asset_Increase_Percentage  Donations_Received  Campaign_Expenses  \
0                                  0.2            45233.93           70890.02
1                                  0.4           105137.99          208466.47
2                                  0.4            40416.75           48765.39
3                                  0.2            95482.42           27702.16
4                                  0.4           141262.03           43989.04

  Business_Ties  Previous_Complaints  Is_Suspicious
0           Yes                    0              0
1            No                    1              0
2           Yes                    1              1
3           Yes                    2              0
4      Declared                    2              0